import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

export default function FAQSection() {
  const faqs = [
    {
      question: 'How do I use a lease code?',
      answer:
        'Copy the lease code from this site by clicking the "Copy Code" button on any available listing. Then open the Unity Network app on your smartphone, navigate to the Lease or Claim section, and paste the code. Tap Activate or Submit to confirm. Each code is single-use — once claimed, it cannot be used again by anyone else.',
    },
    {
      question: 'Can lease codes be reused?',
      answer:
        'No. Every lease code is strictly single-use. Once you activate a code in the Unity app, it is permanently bound to your account and will show as "Unavailable" on this site. If you see a code marked Unavailable, please select a different one that is still Available.',
    },
    {
      question: 'What happens if a code shows as unavailable?',
      answer:
        'An "Unavailable" status means the code has already been claimed by another user. The copy button is disabled for these codes to prevent confusion. Simply scroll through the listings and choose any code that shows a green "Available" badge.',
    },
    {
      question: 'What rewards can I earn?',
      answer:
        'Unity License Operators (ULOs) typically receive 75% of the network rewards generated by their device. Some leases on this site offer customized splits (e.g., 60/40 or other ratios) — the exact percentage is shown on each listing card. Rewards are distributed in ULO tokens based on your device\'s contribution to the mobile edge network.',
    },
    {
      question: 'What devices are compatible?',
      answer:
        'The Unity Network app supports modern iOS devices (iPhone running iOS 14 or later) and Android smartphones (Android 8.0 or later). Your device should have a stable internet connection — Wi-Fi or mobile data — and sufficient battery or be plugged in for continuous operation. Check the App Store or Google Play listing for the latest compatibility details.',
    },
    {
      question: 'How often are lease codes updated?',
      answer:
        'New lease codes are added regularly by the node operator (A304). This page auto-refreshes every 60 seconds so you always see the latest availability. For real-time updates and announcements about new code drops, follow @UnityNodesIO on X.',
    },
    {
      question: 'What is a split ratio?',
      answer:
        'The split ratio defines how the rewards earned through a lease are divided between the Unity Node Operator (UNO) and the Unity License Operator (ULO). For example, a 60/40 split means the UNO receives 60% and the ULO receives 40% of all rewards generated. Higher ULO percentages mean more earnings for you as the device operator.',
    },
    {
      question: 'How do I get started?',
      answer:
        '1. Download the Unity Network app from the App Store (iOS) or Google Play (Android). 2. Create your account and complete any in-app verification steps. 3. Return to this page and copy an available lease code. 4. In the Unity app, go to the Lease / Claim section and enter the code. 5. Your device will begin contributing to the network and earning rewards automatically.',
    },
  ];

  return (
    <section id="faq" className="py-16 sm:py-20 bg-muted/30">
      <div className="container px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl sm:text-4xl font-bold text-center mb-4">Frequently Asked Questions</h2>
        <p className="text-center text-muted-foreground mb-12 max-w-2xl mx-auto">
          Everything you need to know about Unity leasing, lease codes, and earning rewards.
        </p>
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left text-sm sm:text-base min-h-[44px] py-4">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground text-sm sm:text-base leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
