/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ListingID = IDL.Nat;
export const LeaseListing = IDL.Record({
  'nickname' : IDL.Text,
  'listingId' : ListingID,
  'availability' : IDL.Bool,
  'leaseCode' : IDL.Text,
  'splitRatio' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLeaseListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ListingID],
      [],
    ),
  'deleteLeaseListing' : IDL.Func([ListingID], [], []),
  'getAllLeaseListings' : IDL.Func([], [IDL.Vec(LeaseListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListingId' : IDL.Func([IDL.Text], [IDL.Opt(ListingID)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLeaseListing' : IDL.Func(
      [ListingID, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'verifyIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ListingID = IDL.Nat;
  const LeaseListing = IDL.Record({
    'nickname' : IDL.Text,
    'listingId' : ListingID,
    'availability' : IDL.Bool,
    'leaseCode' : IDL.Text,
    'splitRatio' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLeaseListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ListingID],
        [],
      ),
    'deleteLeaseListing' : IDL.Func([ListingID], [], []),
    'getAllLeaseListings' : IDL.Func([], [IDL.Vec(LeaseListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListingId' : IDL.Func([IDL.Text], [IDL.Opt(ListingID)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLeaseListing' : IDL.Func(
        [ListingID, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'verifyIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };